name: Run Script on Push

on: 
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run the script with secrets
      run: bash deploy_to_griefbox.sh
      env:
        SSH_USERNAME: ${{ secrets.GRIEFBOX_SSH_USERNAME }}
        SSH_HOST: ${{ secrets.GRIEFBOX_SSH_HOST }}
        SSH_KEY: ${{ secrets.GRIEFBOX_SSH_KEY_ECDSA }}
