name: Run Script on Push

on: 
  push:
    branches:
      - '*'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add execute permissions to script
      run: chmod +x ./.github/workflows/deploy_to_griefbox.sh

    - name: Run the script with secrets
      run: bash ./.github/workflows/deploy_to_griefbox.sh
      env:
        SSH_USERNAME: ${{ secrets.GRIEFBOX_SSH_USERNAME }}
        SSH_HOST: ${{ secrets.GRIEFBOX_SSH_HOST }}
        SSH_KEY: ${{ secrets.GRIEFBOX_SSH_KEY_RSA }}
        KNOWN_HOSTS: ${{ secrets.GRIEFBOX_KNOWN_HOSTS_KEYS }}
